# Generated by Django 4.2.4 on 2023-12-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_options_posts_created_on_posts_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
