# Generated by Django 4.2.4 on 2023-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_created_on_alter_posts_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics/'),
        ),
    ]
