# Generated by Django 4.2.4 on 2023-12-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stage_name',
            field=models.CharField(default='Fleek Poetry', max_length=100),
        ),
    ]
